version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "
        until pg_isready -h db -p 5432 -U ${POSTGRES_USER}; do
          echo 'Waiting for Postgres...'; sleep 2; 
        done &&
        bundle exec rails db:create db:migrate &&
        bundle exec puma -C config/puma.rb
      "
    volumes:
      - .:/app
      - ./config/master.key:/app/config/master.key:ro
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: db                  # <-- IMPORTANT: match Compose service name
      RAILS_ENV: development
    depends_on:
      - db

volumes:
  db_data:
