default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "password" %>
  host: <%= ENV["DB_HOST"] || "localhost" %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "budget_app_development" %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
